// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[playbackId].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/api/listen/[playbackId].ts";
import * as $3 from "./routes/api/webhook.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Player.tsx";

const manifest = {
  routes: {
    "./routes/[playbackId].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/api/listen/[playbackId].ts": $2,
    "./routes/api/webhook.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Player.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
